version : "3.7"

services:
  front:
    container_name: front
    build: frontend
    restart: always
    volumes:
      - ./frontend/src/back.js:/app/src/back.js
    ports:
     - "3000:3000"

  back:
    container_name: back
    build: backend
    ports:
    - "5000:5000"