version : "3.7"

services:
  pgre:
    container_name: pgre
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: "${pgrePass}"
    volumes:
      - "db:/var/lib/postgresql/data"


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${mongoUser}"
      MONGO_INITDB_ROOT_PASSWORD: "${mongoPass}"


volumes:
  db: