version : "3.7"

services:
  front:
    container_name: front
    build: frontend
    restart: always
    ports:
     - "3000:3000"

  back:
    container_name: back
    build: backend
    expose: [5000]