- hosts: all

  tasks:
    - name: Read repo file
      ansible.builtin.shell: "cat ~/remote-files/repo"
      register: repofile

    - name: Set repo
      set_fact:
        aws_ECR_URL: "{{ repofile.stdout }}"    

    - name: Get aws password
      ansible.builtin.shell: "aws ecr get-login-password"
      register: awsPass

    - name: Docker login
      become: yes
      community.docker.docker_login:
        registry_url: "{{ aws_ECR_URL }}"
        username: AWS
        password: "{{awsPass.stdout}}"

    - name: Pulling postgres image
      become: yes
      community.docker.docker_image:
        name: postgres
        source: pull
        pull:

    - name: Pulling mongo image
      become: yes
      community.docker.docker_image:
        name: mongo
        source: pull
        pull:

    - name: Building front image
      become: yes
      community.docker.docker_image:
        name: frontend
        build:
          path: /home/{{ ansible_user }}/ecommerce/front-back/frontend
        source: build

    - name: Building back image
      become: yes
      community.docker.docker_image:
        name: backend
        build:
          path: /home/{{ ansible_user }}/ecommerce/front-back/backend
        source: build
    

    - name: Pushing postgres
      become: yes
      community.docker.docker_image:
        name: postgres
        repository: "{{aws_ECR_URL}}/postgres:latest"
        push: true
        source: local

    - name: Pushing mongo
      become: yes
      community.docker.docker_image:
        name: mongo
        repository: "{{aws_ECR_URL}}/mongo:latest"
        push: true
        source: local

    - name: Pushing frontend
      become: yes
      community.docker.docker_image:
        name: frontend
        repository: "{{aws_ECR_URL}}/frontend:latest"
        push: true
        source: local

    - name: Pushing backend
      become: yes
      community.docker.docker_image:
        name: backend
        repository: "{{aws_ECR_URL}}/backend:latest"
        push: true
        source: local
    

    ############
    # Run
    ############

    - name: Run ansible
      shell: "echo ansible-playbook playbookVM.yml --private-key   ~/remote-files/ecommerce-key -i ~/remote-files/hosts"
      register: ansible
      args:
       chdir: /home/{{ ansible_user }}/ecommerce/automation/ansible/VM

    - debug:
        var: ansible.stdout_lines
