- name: docker installation
  strategy: free
  hosts: all
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:    
    ##################
    #	ssh
    #################
    - name: copying file with the pub keys
      tags: ssh
      copy:
        src: /home/{{ ansible_user }}/pkeys/temp.txt
        dest: /home/{{ ansible_user }}/sshKeys

    - name: setting authorized pub keys
      tags: ssh
      become: true
      shell: "cat sshKeys >> /home/{{ ansible_user }}/.ssh/authorized_keys"
      args:
        chdir: /home/{{ ansible_user }}


    ##################
    #	Install
    #################
    - name: Update apt
      tags: dep
      become: yes
      apt:
        update_cache: true

    - name: Install docker
      tags: dep
      become: true
      snap:
        name: docker

    - name: Install pip
      tags: dep
      become: yes
      shell: "wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py"

    - name: Install python docker libs
      tags: dep
      become: yes
      apt:
        name: python3-docker

    - name: Install python docker compose libs
      tags: dep
      become: yes
      pip:
        name: docker-compose

    ##################
    #	AWS ECR login
    #################
    - name: Read repo file
      tags: ecr
      ansible.builtin.shell: "cat ~/remote-files/repo"
      register: repofile
      delegate_to: localhost
      run_once: true

    - name: Set repo
      tags: ecr
      set_fact:
        aws_ECR_URL: "{{ repofile.stdout }}"    
      delegate_to: localhost
      run_once: true

    - name: Get aws password
      tags: ecr
      ansible.builtin.shell: "aws ecr get-login-password"
      register: awsPass
      delegate_to: localhost
      run_once: true

    - name: Docker login
      tags: ecr
      become: yes
      community.docker.docker_login:
        registry_url: "{{ aws_ECR_URL }}"
        username: AWS
        password: "{{awsPass.stdout}}"


    #################
    #	BANCO
    ################
    - name: read db vars
      tags: db
      include_vars: /home/{{ ansible_user }}/remote-files/ansible-vars.yaml
      when: "'db' in group_names"

    - name: copying db files
      tags: db
      copy:
        src: /home/{{ ansible_user }}/ecommerce/banco
        dest: /home/{{ ansible_user }}
      when: "'db' in group_names"

    - name: copying db env
      tags: db
      copy:
        src: /home/{{ ansible_user }}/remote-files/dbenv
        dest: /home/{{ ansible_user }}/banco/.env
      when: "'db' in group_names"

    - name: copying docker clean script
      tags: db
      copy:
        src: /home/{{ ansible_user }}/remote-files/clean
        dest: /home/{{ ansible_user }}/banco/clean
      when: "'db' in group_names"

    - name: running docker
      tags: db
      become: yes
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/banco
        build: false
        env_file: /home/{{ ansible_user }}/banco/.env #require .env file
        recreate: "always"
        remove_orphans : true
      register: output
      when: "'db' in group_names"

    - debug:
        var: output
      tags: db
      when: "'db' in group_names"

    - name: Waiting for postgres to initialize
      tags: db
      wait_for:
        timeout: 5
      when: "'db' in group_names"
      delegate_to: localhost

    - name: "Create app database"
      tags: db
      postgresql_db:
        name: "{{pgrDB}}"	
        login_host: "{{pgreHost}}"
        login_user: "{{pgreUser}}"
        login_password: "{{pgrePass}}"
      when: "'db' in group_names"
      delegate_to: localhost

    - name: "Init database UID"
      tags: db
      postgresql_query:
        db: "{{pgrDB}}"	
        query: "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\""
        login_host: "{{pgreHost}}"
        login_user: "{{pgreUser}}"
        login_password: "{{pgrePass}}"
      when: "'db' in group_names"
      delegate_to: localhost

    - name: "Create app table"
      tags: db
      postgresql_table:
        db: "{{pgrDB}}"	
        table: "{{pgrTable}}"
        columns: ["sku UUID PRIMARY KEY", "product_name VARCHAR (255) NOT NULL", "description VARCHAR(255)", "price NUMERIC(10,2) NOT NULL", "quantity INT NOT NULL", "image_link VARCHAR (255) NOT NULL"]
        login_host: "{{pgreHost}}"
        login_user: "{{pgreUser}}"
        login_password: "{{pgrePass}}"
      when: "'db' in group_names"
      delegate_to: localhost



    #################
    #	LOG
    ################
    - name: copying IPs to log vm
      tags: log
      copy:
        src: /home/{{ ansible_user }}/remote-files/hosts
        dest: /home/{{ ansible_user }}/ips
      when: "'grafana' in group_names"

    - name: make var/data dir
      tags: log
      file:
        path: /home/{{ ansible_user }}/monitoring
        state: directory
      when: "'grafana' in group_names"

    - name: Copiar docker-compose local p servidor
      tags: log
      copy:
        src: "/home/{{ ansible_user }}/ecommerce/grafana-prometheus-compose/docker-compose.yml"
        dest: "/home/{{ ansible_user }}/monitoring"
      when: "'grafana' in group_names"

    - name: Copiar prometheus.yml local p servidor
      become: true
      tags: log
      copy:
        src: "/home/{{ ansible_user }}/remote-files/prometheus.yml"
        dest: "/home/{{ ansible_user }}/monitoring/prometheus/"
      when: "'grafana' in group_names"

    - name: running docker-compose file
      become: true
      tags: log
      docker_compose:
        project_src: /home/{{ ansible_user }}/monitoring
        state: present
      when: "'grafana' in group_names"

    #################
    #	Nginx
    ################
    - name: copying nginx files
      tags: lb
      copy:
        src: /home/{{ ansible_user }}/ecommerce/nginx
        dest: /home/{{ ansible_user }}
      when: "'nginx' in group_names"

    - name: copying docker env to nginx
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/frontenv
        dest: /home/{{ ansible_user }}/nginx/.env
      when: "'nginx' in group_names"

    - name: copying nginx conf
      tags: lb
      copy:
        src: /home/{{ ansible_user }}/remote-files/nginx.conf
        dest: /home/{{ ansible_user }}/nginx/nginx.conf
      when: "'nginx' in group_names"

    - name: running docker
      tags: lb
      become: yes
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/nginx
        recreate: "always"
        remove_orphans : true
      register: output
      when: "'nginx' in group_names"

    - debug:
        var: output
      tags: lb
      when: "'nginx' in group_names"

    #################
    #	Front/Back app
     ################
    - name: copying front files
      tags: app
      copy:
        src: /home/{{ ansible_user }}/ecommerce/front-back
        dest: /home/{{ ansible_user }}
      when: "'front-back' in group_names or 'app-hs' in group_names"

    - name: copying docker clean script
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/clean
        dest: /home/{{ ansible_user }}/front-back/clean
      when: "'front-back' in group_names or 'app-hs' in group_names"

    - name: copying docker env to front
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/frontenv
        dest: /home/{{ ansible_user }}/front-back/.env
      when: "'front-back' in group_names or 'app-hs' in group_names"

    - name: copying back to front
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/back.js
        dest: /home/{{ ansible_user }}/front-back/frontend/src/back.js
      when: "'front-back' in group_names"

    - name: copying back to HS
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/backHS.js
        dest: /home/{{ ansible_user }}/front-back/frontend/src/back.js
      when: "'app-hs' in group_names"

    - name: copying .env to front
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/dotenv
        dest: /home/{{ ansible_user }}/front-back/frontend/.env
      when: "'front-back' in group_names or 'app-hs' in group_names"

    - name: copying .env to back
      tags: app
      copy:
        src: /home/{{ ansible_user }}/remote-files/dotenv
        dest: /home/{{ ansible_user }}/front-back/backend/.env
      when: "'front-back' in group_names or 'app-hs' in group_names"

#    - name: Pulling images on HS
#      tags: app
#      become: yes
#      community.docker.docker_compose:
#        project_src: /home/{{ ansible_user }}/front-back
#        pull: true
#        state: absent
#        remove_orphans : true
#      register: output
#      when: "'app-hs' in group_names"
#
    - name: running docker
      tags: app
      become: yes
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/front-back
        build: true
        recreate: "always"
        remove_orphans : true
      register: output
      #when: "'front-back' in group_names"
      when: "'front-back' in group_names or 'app-hs' in group_names"

    - debug:
        var: output
      tags: app
      when: "'front-back' in group_names"
