version : "3.7"

services:
  front:
    container_name: nginx
    image: "${awsRepo}/nginx:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "3000:3000"