- hosts: all
  become: true
  become_user: root

  tasks:
    - name: download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /tmp

    - name: unarchive node exporter
      unarchive:
        remote_src: yes
        src: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /tmp

    - name: move node exporter to /usr/local/bin
      copy:
        src: /tmp/node_exporter-0.18.1.linux-amd64/node_exporter
        dest: /usr/local/bin/
        remote_src: yes
        owner: root
        group: root
        mode: 0755

    - name: useradd -rs node-exporter
      shell:
        "sudo useradd -rs /bin/false node_exporter"

    - name: install unit file to systemd
      template:
        src: "{{ playbook_dir }}/../ansible-node-exporter/node_exporter.service.j2"
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0600

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: node_exporter.service

    - name: Reload service node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted